name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure and build
        run: |
          cmake -G Ninja -B build
          cd build
          ninja
      - name: Run tests
        run: ctest
